# Hacemos las configuraciones de H2
# === Datasource H2 en memoria solo para tests ===
spring.datasource.url=jdbc:h2:mem:vetdb;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_UPPER=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=vetuser
spring.datasource.password=

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
# Logging de pruebas más limpio
logging.level.org.springframework.test=INFO

# JWT configuración para Tests
# Si no existe la variable PRIVATE_KEY, usa el texto después de los dos puntos
security.jwt.private.key=${PRIVATE_KEY:mi_clave_secreta_de_prueba_muy_larga_para_que_el_algoritmo_no_falle_12345678}
security.jwt.user.generator=${USER_GENERATOR:test_user_generator}