spring.application.name=e_commerce

#configuraciones de BD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
#jdbc:mysql://localhost:3306/eCommerce?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#JWT configuracion
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}

# Crea el archivo y lo mantiene actualizado config para los log
logging.file.name=logs/e_commerce.log
# (Opcional) Define cuanto debe pesar el archivo antes de crear uno nuevo
logging.logback.rollingpolicy.max-file-size=10MB
# Solo loguea errores y advertencias de las librerias de Spring
logging.level.org.springframework=INFO
# Loguea todo INFO WARN ERROR de TU propio codigo
logging.level.com.e_commerce=INFO




